-- MySQL Script generated by MySQL Workbench
-- 03/30/16 15:34:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`ubicaciones` (
  `idUbicacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idUbicacion`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 119
DEFAULT CHARACTER SET = utf8;
TRUNCATE table`inventario`.`ubicaciones`;

-- -----------------------------------------------------
-- Table `inventario`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`articulos` (
  `idArticulo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tomo` INT(11) NOT NULL COMMENT '',
  `folio` INT(11) NOT NULL COMMENT '',
  `asiento` INT(11) NOT NULL COMMENT '',
  `idEtiqueta` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `marca` VARCHAR(45) NOT NULL COMMENT '',
  `modelo` VARCHAR(45) NOT NULL COMMENT '',
  `serie` VARCHAR(45) NOT NULL COMMENT '',
  `condicion` VARCHAR(45) NOT NULL COMMENT '',
  `idUbicacion` INT(11) NOT NULL COMMENT '',
  `adquisicion` VARCHAR(45) NOT NULL COMMENT '',
  `observaciones` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idArticulo`)  COMMENT '',
  INDEX `idUbicacion_idx` (`idUbicacion` ASC)  COMMENT '',
  CONSTRAINT `idUbicacion`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `inventario`.`ubicaciones` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2965
DEFAULT CHARACTER SET = utf8;
TRUNCATE table`inventario`.`articulos`;

-- -----------------------------------------------------
-- Table `inventario`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`roles` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `operacion` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`idRol`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;
TRUNCATE table`inventario`.`roles`;

-- -----------------------------------------------------
-- Table `inventario`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido1` VARCHAR(45) NOT NULL COMMENT '',
  `apellido2` VARCHAR(45) NOT NULL COMMENT '',
  `nombreUsuario` VARCHAR(45) NOT NULL COMMENT '',
  `clave` VARCHAR(45) NOT NULL COMMENT '',
  `idRol` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  INDEX `idRol_idx` (`idRol` ASC)  COMMENT '',
  CONSTRAINT `idRol_FK`
    FOREIGN KEY (`idRol`)
    REFERENCES `inventario`.`roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;
TRUNCATE table`inventario`.`usuarios`;

-- -----------------------------------------------------
-- Table `inventario`.`registros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`registros` (
  `idRegistro` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(400) NOT NULL COMMENT '',
  `idUsuario` INT(11) NOT NULL COMMENT '',
  `timeStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idRegistro`)  COMMENT '',
  INDEX `idUsuario_idx` (`idUsuario` ASC)  COMMENT '',
  CONSTRAINT `idUsuario_FK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `inventario`.`usuarios` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3237
DEFAULT CHARACTER SET = utf8;
TRUNCATE table`inventario`.`registros`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `inventario`.`roles`(descripcion, operacion) 
VALUES ('administrador','PERMISO_TODO');

INSERT INTO `inventario`.`usuarios` (nombre,apellido1,apellido2,nombreUsuario,clave,idRol)VALUES('Administrador','','','admin','70e76a15da0e6301ade718cc9416f79',1);
/*clave is adminpw*/

