package utilidades;

public class Enumeracion {

	public static enum Operaciones {
		PERMISO_TODO, EDITAR_USUARIO, EDITAR_ARTICULO, EDITAR_ROL, EDITAR_UBICACION, MOSTRAR_USUARIO, MOSTRAR_ARTICULO, MOSTRAR_ROL, MOSTRAR_UBICACION;
	}
}